export const SIGN_IN = "SIGN_IN";
export const CHANGE_BACKGROUND_COLOR = "CHANGE_BACKGROUND_COLOR";
export const SELECT_BACKGROUND_IMAGE = "SELECT_BACKGROUND_IMAGE";
export const DELETE_BACKGROUND_IMAGE = "DELETE_BACKGROUND_IMAGE";
export const ADD_SHAPE = "ADD_SHAPE";
export const SUBMIT_POSTER_FORM = "SUBMIT_POSTER_FORM";